language: csharp
mono: none
dotnet: 2.1.403
solution: HoneyDo.sln
script:
  - "./test.sh"
branches:
  only:
    - develop
    - master
deploy:
  provider: heroku
  api_key:
    - secure: wZOxDMIRoHDELoa9opZJajx5UwTpgguVT7Md2xJ2qdn7kwSKlzpcsd2VGSOd0Sx6+H/l4LksragRK1vA/Xw7cWgGcnJi5XpgMgekRJmzECG/oYnIxCHzzzITkndyaKAkCvLSkvkdkWzfL276b24p49Gu79Ny8pNaGjbEHkSGJoi501VNWFct8/M+6YMM4XzbYdkQb/egvkXE8/2id+NVl4Zqg9sEavfkdY7AbuasdSeKTyyRAm9cMfbCff1KLkMfeM+TFU3wUIe6D2jNrQh4oE8mwTYwkwD4ULig2nuGZa+7BYDR4j8uICa0bUhf1CPDUqoV8JlyL8aLCEbujrptedPr2FjOCKSSIUf/uHrAjl+oeKPFPClVkYG7KU/6OBg4LOHBAXcOHGtrizho6/rKJ43gj2I7f77OY8GcA6eUzsvmQ8miTbOb26+9js+KYpv58dqDc2cD+Bko+nY22aGmvxyosbEYvmJpxcfO75/uGf+94zFaBajUohL0XmnHjqoIl25OYiQq2YfZr1i7YGsdCTgnrXKo8BpUurGePOqpCtlqDJVIOOheCmNMdqUHRuk+L53yuPPiD0th8qJRKmCqeXijNEWFNz+yAi8rT0QT0cjLXdPBzo8XM/HYSQbfBRFf/Bkl+bbBD33BUrDDoV03bx2WCU/UvXjpIqNpf7GeTyw=
  app:
    - develop: honey-dos-stage
    - master: honey-dos
  on:
    repo: honey-dos/web
    branch:
      - develop
      - master
