language: csharp
mono: none
dotnet: 2.1.403
solution: HoneyDo.sln
script:
  - "./test.sh"
branches:
  only:
    - develop
    - master
deploy:
  provider: heroku
  api_key:
    secure: ATLyhFaEHpEPGkMJKHDw8sfo6tzVrAVuUlzRY+SpQls9pv08wNW0GgjQ8mRxDDRaRN/TabQO4rsoBC21SZxpg1vFe/hVWo3qmUR/kceuI2OaZlbXkJAbYzOTfuEpCjGu1oGG0NVp64BBY90XpNNbkaooVrdDBLfa4BqL7m/YVeFQaPr2urkAnFModpo6vjUDiUbdaj/YgZjWNodszolbeWMofeDiMSEroMqI6/cyZQ3v8ZzmHxBcgHJqNysZhIJfQAXHKPoHh8/vL8URQH1UmixzRmLixCXd/fmuLfgGR3TAMGuANBrnKL5V9ZvixQ4TB2+GKEqgFYP4ZXtpHaNx2r4U8hrZSCXTkTVXJMwjjSWCVLnzJy2nJf7SEvjvwJrginKslbdUFkKiHy6t1Jxz8joTS8pASoPULSzcsEsAnfpnxb6a/bDMyA2YartycjjWZW/OoLaxKSjz1LnNVQf4krqAmrnrzLLdwXXxAHJAXSCJJCQMA7JbbmcWzakOjey3pddwr5I8WfbovB2azI9Ufao0KXHDC2+fXq/Ll9As48jyOnDVqTP1vmxV4gqX0J7/8gWtXMpCZI5ka4vrbhbnLaPJ2nUsQQXtI4Vc2CEiVXLGKPBeUvZFJ8aSDlMDrO+7N7dBJzYMcKAhCuzI957n5Pa238RgnCoaNhOySZ4SneE=
  app:
    develop: honey-dos-stage
    master: honey-dos
  on:
    repo: honey-dos/web
